import type { ScanReport } from '../types';

export function exportJson(report: ScanReport): void {
  const blob = new Blob([JSON.stringify(report, null, 2)], {
    type: 'application/json',
  });
  downloadBlob(blob, `security-report-${report.overview.hostname}-${Date.now()}.json`);
}

export function exportTxt(report: ScanReport): void {
  const lines: string[] = [
    '='.repeat(70),
    `PASSIVE WEB SECURITY ANALYZER PRO — REPORT`,
    '='.repeat(70),
    `Target:        ${report.overview.hostname}`,
    `Final URL:     ${report.overview.finalUrl}`,
    `Scanned:       ${new Date(report.timestamp).toLocaleString()}`,
    `Risk Score:    ${report.riskScore.score}/100 (${report.riskScore.label})`,
    `Findings:      ${report.findings.length}`,
    '',
    '─'.repeat(70),
    'RISK SCORE',
    '─'.repeat(70),
    report.riskScore.rationale,
    '',
    '─'.repeat(70),
    'FINDINGS',
    '─'.repeat(70),
  ];

  for (const f of report.findings) {
    lines.push('');
    lines.push(`[${f.severity.toUpperCase()}] ${f.title}`);
    lines.push(`Category:  ${f.category}`);
    lines.push(`Evidence:  ${f.evidence}`);
    lines.push(`Details:   ${f.technicalDetails}`);
    lines.push(`Fix:       ${f.recommendation}`);
  }

  lines.push('');
  lines.push('─'.repeat(70));
  lines.push('SECURITY HEADERS');
  lines.push('─'.repeat(70));

  for (const h of report.headers) {
    lines.push(`${h.present ? '✓' : '✗'} ${h.name}: ${h.value || 'NOT PRESENT'}`);
  }

  lines.push('');
  lines.push('─'.repeat(70));
  lines.push('SSL/TLS');
  lines.push('─'.repeat(70));
  if (report.ssl.available) {
    lines.push(`Subject:         ${report.ssl.subject || 'N/A'}`);
    lines.push(`Issuer:          ${report.ssl.issuer || 'N/A'}`);
    lines.push(`Valid From:      ${report.ssl.validFrom || 'N/A'}`);
    lines.push(`Valid To:        ${report.ssl.validTo || 'N/A'}`);
    lines.push(`Days Remaining:  ${report.ssl.daysRemaining ?? 'N/A'}`);
  } else {
    lines.push('HTTPS not available');
  }

  lines.push('');
  lines.push('─'.repeat(70));
  lines.push('DNS RECORDS');
  lines.push('─'.repeat(70));
  for (const [type, record] of Object.entries({
    A: report.dns.a,
    AAAA: report.dns.aaaa,
    MX: report.dns.mx,
    NS: report.dns.ns,
  })) {
    const rec = record as { values: string[]; status: string };
    lines.push(`${type}: ${rec.values.length > 0 ? rec.values.join(', ') : `(${rec.status})`}`);
  }

  lines.push('');
  lines.push('─'.repeat(70));
  lines.push('RECOMMENDATIONS');
  lines.push('─'.repeat(70));
  for (const r of report.recommendations) {
    lines.push(`[${r.priority.toUpperCase()}] ${r.title}`);
    lines.push(`  ${r.reason}`);
    lines.push('');
  }

  lines.push('='.repeat(70));
  lines.push('Generated by Passive Web Security Analyzer Pro');
  lines.push('='.repeat(70));

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  downloadBlob(blob, `security-report-${report.overview.hostname}-${Date.now()}.txt`);
}

export function exportHtml(report: ScanReport): void {
  const severityColor = (s: string): string => {
    const map: Record<string, string> = {
      critical: '#ef4444',
      high: '#f97316',
      moderate: '#eab308',
      low: '#3b82f6',
      info: '#6b7280',
    };
    return map[s] || '#6b7280';
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Security Report — ${report.overview.hostname}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #060810; color: #e2e8f0; line-height: 1.6; padding: 2rem; }
  h1 { font-size: 1.8rem; color: #00d4ff; margin-bottom: 0.25rem; }
  h2 { font-size: 1.1rem; color: #94a3b8; margin: 2rem 0 1rem; border-bottom: 1px solid #1e2a3a; padding-bottom: 0.5rem; }
  .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 2rem; }
  .score-box { display: inline-block; background: #111827; border: 1px solid #1e2a3a; border-radius: 12px; padding: 1rem 2rem; margin-bottom: 2rem; }
  .score-num { font-size: 3rem; font-weight: 700; color: #00d4ff; }
  .score-label { color: #94a3b8; font-size: 0.875rem; }
  .finding { background: #111827; border: 1px solid #1e2a3a; border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; border-left: 3px solid; }
  .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; color: #fff; margin-bottom: 0.5rem; }
  .header-row { display: flex; gap: 1rem; padding: 0.5rem 0; border-bottom: 1px solid #1e2a3a; align-items: center; font-size: 0.875rem; }
  .present { color: #34d399; }
  .missing { color: #f87171; }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  td, th { padding: 0.5rem 0.75rem; border-bottom: 1px solid #1e2a3a; text-align: left; }
  th { color: #64748b; font-weight: 500; }
  .mono { font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; color: #94a3b8; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #1e2a3a; color: #475569; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>Security Report</h1>
<p class="meta">${report.overview.hostname} · Scanned ${new Date(report.timestamp).toLocaleString()}</p>

<div class="score-box">
  <div class="score-num">${report.riskScore.score}<span style="font-size:1.2rem;color:#64748b">/100</span></div>
  <div class="score-label">Risk Score · ${report.riskScore.label}</div>
</div>

<p style="color:#94a3b8;font-size:0.875rem;margin-bottom:2rem">${report.riskScore.rationale}</p>

<h2>Findings (${report.findings.length})</h2>
${report.findings
  .map(
    (f) => `
<div class="finding" style="border-left-color:${severityColor(f.severity)}">
  <span class="badge" style="background:${severityColor(f.severity)}">${f.severity}</span>
  <strong>${f.title}</strong>
  <p style="color:#94a3b8;font-size:0.875rem;margin-top:0.4rem">${f.technicalDetails}</p>
  <p style="color:#64748b;font-size:0.8rem;margin-top:0.3rem"><em>Fix: ${f.recommendation}</em></p>
</div>`
  )
  .join('')}

<h2>Security Headers</h2>
${report.headers
  .map(
    (h) => `
<div class="header-row">
  <span class="${h.present ? 'present' : 'missing'}">${h.present ? '✓' : '✗'}</span>
  <span style="flex:1">${h.name}</span>
  <span class="mono">${h.value || '—'}</span>
</div>`
  )
  .join('')}

<h2>SSL/TLS</h2>
${
  report.ssl.available
    ? `<table>
  <tr><th>Subject</th><td class="mono">${report.ssl.subject || 'N/A'}</td></tr>
  <tr><th>Issuer</th><td class="mono">${report.ssl.issuer || 'N/A'}</td></tr>
  <tr><th>Valid From</th><td>${report.ssl.validFrom || 'N/A'}</td></tr>
  <tr><th>Valid To</th><td>${report.ssl.validTo || 'N/A'}</td></tr>
  <tr><th>Days Remaining</th><td>${report.ssl.daysRemaining ?? 'N/A'}</td></tr>
</table>`
    : '<p style="color:#64748b">HTTPS not available</p>'
}

<h2>DNS Records</h2>
<table>
  <tr><th>Type</th><th>Values</th><th>Status</th></tr>
  ${[
    ['A', report.dns.a],
    ['AAAA', report.dns.aaaa],
    ['MX', report.dns.mx],
    ['NS', report.dns.ns],
  ]
    .map(
      ([t, r]) =>
        `<tr><td>${t}</td><td class="mono">${(r as { values: string[] }).values.join(', ') || '—'}</td><td style="color:#64748b;font-size:0.8rem">${(r as { status: string }).status}</td></tr>`
    )
    .join('')}
  <tr><td>SPF</td><td class="mono">${report.dns.spfRecord || '—'}</td><td style="color:#64748b;font-size:0.8rem">${report.dns.spfFound ? 'Found' : 'Not found'}</td></tr>
  <tr><td>DMARC</td><td class="mono">${report.dns.dmarcRecord || '—'}</td><td style="color:#64748b;font-size:0.8rem">${report.dns.dmarcFound ? 'Found' : 'Not found'}</td></tr>
</table>

<footer>Generated by Passive Web Security Analyzer Pro · Passive analysis only · No intrusive scanning performed</footer>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, `security-report-${report.overview.hostname}-${Date.now()}.html`);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
